services:
  mlflow:
    restart: always
    build: ./mlflow
    image: mlflow_server
    container_name: mlflow_server
    command: mlflow server --backend-store-uri postgresql+psycopg2://postgres:postgres@postgres:5432/mlflow_db --host 0.0.0.0 -p 5001
    ports:
      - "5001:5001"
    depends_on:
      - postgres
      - minio

  postgres:
    image: postgres:14.2
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mlflow_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    container_name: minio_storage
    environment:
      MINIO_ROOT_USER: mino
      MINIO_ROOT_PASSWORD: minopassword
    command: server --console-address ":9001" /data
    volumes:
      - minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  postgres: { }
  minio: { }
